### PR TITLE
Minor bugfix for constrained covariant type parameters.

### PR DESCRIPTION
**Pull request by TobiasWolters**
---
Rebus is [MIT-licensed](https://opensource.org/licenses/MIT). The code submitted in this pull request needs to carry the MIT license too. By leaving this text in, __I hereby acknowledge that the code submitted in the pull request has the MIT license and can be merged with the Rebus codebase__.

### CODE REVIEW

**Comment by mookid8000** [comment]
Perfect 🙂  it's out as Rebus.ServiceProvider 6.4.1

**Comment by TobiasWolters** [comment]
Thanks 👍

**Comment by TobiasWolters** [comment]
@mookid8000 It seems like the release 6.4.1 was never actually created?

**Comment by mookid8000** [comment]
Ah sorry! Didn't see that the release failed.... should be on NuGet.org in a few minutes now 🙂

**Comment by TobiasWolters** [comment]
Thanks 😄

**Pull request merged**
